### ISSUE TITLE
This is some issue

### ISSUE THREAD

**Issue by U2005248** [U2005248/Test#1]
![Capture](https://user-images.githubusercontent.com/74656089/101266807-7521d500-378d-11eb-8947-a4078809b017.PNG)

There are literally **nothing** over here.
I highly recommend we **delete** this file.

**Comment by U2005248** [comment]
MMBM might want to take a look on this

**Comment by Ron-lol** [comment]
Allright man. I'll do it

**Comment by U2005248** [comment]
Thanks man, appreciate it

**Comment by Ron-lol** [comment]
Done

**Comment by Ron-lol** [comment]
Done
